## AREA FIFTYLAN SETTINGS
a5l:
    paymentReturnUrl: https://localhost:5100/order-check
    user:
        resetUrl: https://localhost:5100/password-reset
        acceptTransferUrl: https://localhost:5100/transfer-accept

    mail:
        sender: LANcie <lancie@ch.tudelft.nl>
        contact: LANcie <lancie@ch.tudelft.nl>
        confirmUrl: https://localhost:5100/register-confirm
        setupUrl: https://localhost:5100/setup

    orderLimit: 5
    ticketLimit: 200
    orderKeepAlive: 15
    ratelimit:
        enabled: false

logging:
    level:
        ch.wisv.areafiftylan: DEBUG

management:
    health:
        mail:
            enabled: false
