## SPRING SETTINGS
spring:
    # TODO: Migrate properties and profiles to new version: https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-Config-Data-Migration-Guide
    config:
        use-legacy-processing: true
    main:
        allow-bean-definition-overriding: true
    thymeleaf:
        mode: HTML5
        encoding: UTF-8

    jpa:
        show-sql: false
        hibernate:
            ddl-auto: validate
        open-in-view: true

logging:
    level:
        org.springframework.boot: INFO
        ch.wisv.areafiftylan: INFO
        org.hibernate.SQL: ERROR
    pattern:
        console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file:
        name: logs/lancie-api.log

server:
    port: 9000
    servlet:
        context-path: /api/v1

# Spring Boot Actuator endpoint settings
management:
    endpoints:
        web:
            base-path: /management
    endpoint:
        logfile:
            enabled: true
