logging:
    file:
        name: /tmp/logs/lancie-api.log

## AREA FIFTYLAN SETTINGS 2023
a5l:
    paymentReturnUrl: https://areafiftylan.nl/order-check
    user:
        resetUrl: https://areafiftylan.nl/password-reset
        acceptTransferUrl: https://areafiftylan.nl/transfer-accept

    mail:
        sender: LANcie <lancie@ch.tudelft.nl>
        contact: LANcie <lancie@ch.tudelft.nl>
        confirmUrl: https://areafiftylan.nl/register-confirm
        year: 2023
    ratelimit:
        enabled: false
        minute: 10
    orderLimit: 15
    ticketLimit: 220
    orderKeepAlive: 15
    year: 2019
