## SPRING SETTINGS
spring:
    main:
        allow-bean-definition-overriding: true
    thymeleaf:
        check-template-location: true
        prefix: classpath:/templates/
        suffix: .html
        mode: HTML5
        encoding: UTF-8
        servlet:
            content-type: text/html

    flyway.enabled: true
    jpa:
        show-sql: false
        hibernate:
            ddl-auto: validate

logging:
    level:
        org.springframework.boot: INFO
        ch.wisv.areafiftylan: INFO
        org.hibernate.SQL: ERROR
    pattern:
        console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: logs/lancie-api.log

server:
    port: 9000
    servlet:
        context-path: /api/v1

# Spring Boot Actuator endpoint settings
management:
    endpoints:
        web:
            base-path: /management
    endpoint:
        logfile:
            enabled: true