spring:
  ## DATABASE PROPERTIES
  data.jpa.repositories.enabled: true
  datasource:
    driver-class-name: org.hsqldb.jdbc.JDBCDriver
    url: jdbc:hsqldb:mem:a5l
    username: sa
    password:
  jpa:
    database: hsql
    database-platform: org.hibernate.dialect.HSQLDialect
    generate-ddl: true
    hibernate.ddl-auto: create
    properties.hibernate.default_schema: PUBLIC
    show-sql: false

  mail:
    host: localhost
    port: 1025

  # THYMELEAF (ThymeleafAutoConfiguration)
  thymeleaf:
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    content-type: text/html

  jackson:
    date-format: com.fasterxml.jackson.databind.util.ISO8601DateFormat


server.context-path: /

logging.config: classpath:log4j2-prod.xml

## AREA FIFTYLAN SETTINGS
a5l:
  paymentReturnUrl: https://areafiftylan.nl/order-check
  user:
    resetUrl: https://areafiftylan.nl/password-reset
    acceptTransferUrl: https://areafiftylan.nl/transfer-accept

  mail:
    sender: LANcie <lancie@ch.tudelft.nl>
    contact: LANcie <lancie@ch.tudelft.nl>
    confirmUrl: https://areafiftylan.nl/register-confirm

  orderLimit: 5
  ticketLimit: 200
